var cordovaApp={f7:null,handleSplashscreen:function(){var f7=cordovaApp.f7;if(!window.navigator.splashscreen||f7.device.electron)return;setTimeout(()=>{window.navigator.splashscreen.hide()},2000)},handleAndroidBackButton:function(){var f7=cordovaApp.f7;const $=f7.$;if(f7.device.electron)return;document.addEventListener('backbutton',function(e){if($('.actions-modal.modal-in').length){f7.actions.close('.actions-modal.modal-in');e.preventDefault();return!1}
if($('.dialog.modal-in').length){f7.dialog.close('.dialog.modal-in');e.preventDefault();return!1}
if($('.sheet-modal.modal-in').length){f7.sheet.close('.sheet-modal.modal-in');e.preventDefault();return!1}
if($('.popover.modal-in').length){f7.popover.close('.popover.modal-in');e.preventDefault();return!1}
if($('.popup.modal-in').length){if($('.popup.modal-in>.view').length){const currentView=f7.views.get('.popup.modal-in>.view');if(currentView&&currentView.router&&currentView.router.history.length>1){currentView.router.back();e.preventDefault();return!1}}
f7.popup.close('.popup.modal-in');e.preventDefault();return!1}
if($('.login-screen.modal-in').length){f7.loginScreen.close('.login-screen.modal-in');e.preventDefault();return!1}
if($('.page-current .searchbar-enabled').length){f7.searchbar.disable('.page-current .searchbar-enabled');e.preventDefault();return!1}
if($('.page-current .card-expandable.card-opened').length){f7.card.close('.page-current .card-expandable.card-opened');e.preventDefault();return!1}
const currentView=f7.views.current;if(currentView&&currentView.router&&currentView.router.history.length>1){currentView.router.back();e.preventDefault();return!1}
if($('.panel.panel-in').length){f7.panel.close('.panel.panel-in');e.preventDefault();return!1}},!1)},handleKeyboard:function(){var f7=cordovaApp.f7;if(!window.Keyboard||!window.Keyboard.shrinkView||f7.device.electron)return;var $=f7.$;window.Keyboard.shrinkView(!1);window.Keyboard.disableScrollingInShrinkView(!0);window.Keyboard.hideFormAccessoryBar(!0);window.addEventListener('keyboardWillShow',()=>{f7.input.scrollIntoView(document.activeElement,0,!0,!0)});window.addEventListener('keyboardDidShow',()=>{f7.input.scrollIntoView(document.activeElement,0,!0,!0)});window.addEventListener('keyboardDidHide',()=>{if(document.activeElement&&$(document.activeElement).parents('.messagebar').length){return}
window.Keyboard.hideFormAccessoryBar(!1)});window.addEventListener('keyboardHeightWillChange',(event)=>{var keyboardHeight=event.keyboardHeight;if(keyboardHeight>0){document.body.style.height=`calc(100% - ${keyboardHeight}px)`;$('html').addClass('device-with-keyboard')}else{document.body.style.height='';$('html').removeClass('device-with-keyboard')}});$(document).on('touchstart','input, textarea, select',function(e){var nodeName=e.target.nodeName.toLowerCase();var type=e.target.type;var showForTypes=['datetime-local','time','date','datetime'];if(nodeName==='select'||showForTypes.indexOf(type)>=0){window.Keyboard.hideFormAccessoryBar(!1)}else{window.Keyboard.hideFormAccessoryBar(!0)}},!0)},init:function(f7){cordovaApp.f7=f7;cordovaApp.handleAndroidBackButton();cordovaApp.handleSplashscreen();cordovaApp.handleKeyboard()},};export default cordovaApp